// EthioMatric+ — Real paper questions per subject/year.
// Add new years by dropping another entry under PAPER_QUESTIONS[subjectId][year].

export type Question = {
  id: number;
  text: string;
  options: string[];
  answer: number;
  explanation: string;
};

const mk = (arr: Omit<Question, "id">[]): Question[] =>
  arr.map((q, i) => ({ id: i + 1, ...q }));

// ─── 2017 E.C. papers (20 questions each) ─────────────────────────────────────

const MATH_2017 = mk([
  { text: "If f(x) = 2x² − 3x + 1, then f(2) = ?", options: ["3", "5", "7", "11"], answer: 0,
    explanation: "f(2) = 2(4) − 3(2) + 1 = 8 − 6 + 1 = 3." },
  { text: "Solve for x: 3x − 7 = 2x + 5", options: ["12", "10", "−12", "2"], answer: 0,
    explanation: "3x − 2x = 5 + 7 → x = 12." },
  { text: "The roots of x² − 5x + 6 = 0 are:", options: ["2 and 3", "1 and 6", "−2 and −3", "3 and 4"], answer: 0,
    explanation: "Factor: (x − 2)(x − 3) = 0." },
  { text: "log₂(32) = ?", options: ["5", "4", "6", "16"], answer: 0,
    explanation: "2⁵ = 32." },
  { text: "sin 30° + cos 60° = ?", options: ["1", "½", "√3/2", "0"], answer: 0,
    explanation: "sin 30° = ½ and cos 60° = ½ → sum = 1." },
  { text: "The derivative of x³ is:", options: ["3x²", "x²", "3x", "x⁴/4"], answer: 0,
    explanation: "d/dx(xⁿ) = n·xⁿ⁻¹." },
  { text: "∫₀¹ 2x dx = ?", options: ["1", "2", "½", "0"], answer: 0,
    explanation: "∫2x dx = x². Evaluate 1 − 0 = 1." },
  { text: "Slope of the line through (1,2) and (3,8):", options: ["3", "2", "6", "4"], answer: 0,
    explanation: "m = (8 − 2)/(3 − 1) = 3." },
  { text: "The distance between (0,0) and (3,4) is:", options: ["5", "7", "4", "√7"], answer: 0,
    explanation: "√(9 + 16) = 5." },
  { text: "If sin θ = 3/5 in Q1, then cos θ = ?", options: ["4/5", "3/4", "5/4", "3/5"], answer: 0,
    explanation: "cos²θ = 1 − 9/25 = 16/25 → cos θ = 4/5." },
  { text: "Area of a circle with radius 7 (use π ≈ 22/7):", options: ["154", "44", "49", "22"], answer: 0,
    explanation: "πr² = (22/7)(49) = 154." },
  { text: "The mean of 4, 8, 10, 12, 16 is:", options: ["10", "12", "8", "9"], answer: 0,
    explanation: "(4+8+10+12+16)/5 = 50/5 = 10." },
  { text: "If A = {1,2,3} and B = {3,4}, then A ∪ B = ?", options: ["{1,2,3,4}", "{3}", "{1,2}", "{1,2,3,4,5}"], answer: 0,
    explanation: "Union combines all unique elements." },
  { text: "Simplify (x²)³:", options: ["x⁶", "x⁵", "3x²", "x⁹"], answer: 0,
    explanation: "(xᵃ)ᵇ = xᵃᵇ." },
  { text: "5! (five factorial) = ?", options: ["120", "60", "24", "720"], answer: 0,
    explanation: "5·4·3·2·1 = 120." },
  { text: "Probability of getting a head in one fair coin toss:", options: ["½", "1", "0", "¼"], answer: 0,
    explanation: "Two equally likely outcomes." },
  { text: "The sum of interior angles of a triangle is:", options: ["180°", "360°", "90°", "270°"], answer: 0,
    explanation: "Basic geometry fact." },
  { text: "Which is a rational number?", options: ["3/4", "√2", "π", "e"], answer: 0,
    explanation: "A ratio of two integers is rational." },
  { text: "If |x − 2| = 5, then x = ?", options: ["7 or −3", "5 or 2", "7 only", "−5 only"], answer: 0,
    explanation: "x − 2 = ±5 → x = 7 or x = −3." },
  { text: "The 10th term of the arithmetic sequence 2, 5, 8, … is:", options: ["29", "27", "30", "32"], answer: 0,
    explanation: "aₙ = a + (n − 1)d = 2 + 9(3) = 29." },
]);

const ENGLISH_2017 = mk([
  { text: "Choose the correctly spelled word:", options: ["Accommodate", "Acommodate", "Accomodate", "Acomodate"], answer: 0,
    explanation: "'Accommodate' has double c and double m." },
  { text: "Synonym of 'benevolent':", options: ["Kind", "Cruel", "Selfish", "Rude"], answer: 0,
    explanation: "Benevolent means well-meaning and kindly." },
  { text: "Antonym of 'transparent':", options: ["Opaque", "Clear", "Visible", "Bright"], answer: 0,
    explanation: "Opaque means not able to be seen through." },
  { text: "Choose the correct sentence:", options: ["She doesn't like coffee.", "She don't likes coffee.", "She not like coffee.", "She isn't like coffee."], answer: 0,
    explanation: "Third person singular uses 'doesn't' + base verb." },
  { text: "Passive voice of 'They built a house':", options: ["A house was built by them.", "A house is built by them.", "A house has built by them.", "A house been built by them."], answer: 0,
    explanation: "Past simple passive: was/were + past participle." },
  { text: "Which is a noun?", options: ["Happiness", "Quickly", "Run", "Beautiful"], answer: 0,
    explanation: "Happiness is an abstract noun." },
  { text: "Pick the preposition: 'The book is ___ the table.'", options: ["on", "in", "at", "by"], answer: 0,
    explanation: "'On' indicates a surface." },
  { text: "Reported speech: He said, 'I am tired.'", options: ["He said that he was tired.", "He said that he is tired.", "He says he was tired.", "He said I am tired."], answer: 0,
    explanation: "Present shifts to past in reported speech." },
  { text: "Choose the correct article: '___ university is nearby.'", options: ["A", "An", "The only", "No article"], answer: 0,
    explanation: "'University' begins with a consonant 'y' sound." },
  { text: "Find the error: 'He don't like tea.'", options: ["don't → doesn't", "He → She", "like → likes", "No error"], answer: 0,
    explanation: "Third person singular takes 'doesn't'." },
  { text: "Plural of 'child':", options: ["Children", "Childs", "Childes", "Childrens"], answer: 0,
    explanation: "'Child' has irregular plural 'children'." },
  { text: "Meaning of the idiom 'break the ice':", options: ["Start a conversation", "Break something cold", "Argue", "Ignore someone"], answer: 0,
    explanation: "Common idiom for easing initial tension." },
  { text: "Choose the correct tense: 'By 2020, she ___ in Addis for ten years.'", options: ["had lived", "lives", "was living", "lived"], answer: 0,
    explanation: "Past perfect for action completed before a past point." },
  { text: "Which is an adverb?", options: ["Quickly", "Quick", "Quickness", "Quicken"], answer: 0,
    explanation: "-ly commonly signals adverbs of manner." },
  { text: "Choose the correct form: 'Neither John nor his friends ___ coming.'", options: ["are", "is", "was", "has"], answer: 0,
    explanation: "Verb agrees with the closer subject 'friends'." },
  { text: "Antonym of 'ancient':", options: ["Modern", "Old", "Aged", "Historic"], answer: 0,
    explanation: "Modern is the opposite of ancient." },
  { text: "Which word is a conjunction?", options: ["Although", "Quickly", "Beautiful", "Under"], answer: 0,
    explanation: "'Although' joins two clauses." },
  { text: "Choose the best question tag: 'You are coming, ___?'", options: ["aren't you", "isn't you", "don't you", "won't you"], answer: 0,
    explanation: "'Are' → 'aren't' in the tag." },
  { text: "Synonym of 'diligent':", options: ["Hardworking", "Lazy", "Careless", "Slow"], answer: 0,
    explanation: "Diligent means showing persistent effort." },
  { text: "Which sentence is grammatically correct?", options: ["She has lived here since 2010.", "She has lived here for 2010.", "She lives here since 2010.", "She living here since 2010."], answer: 0,
    explanation: "'Since' + point in time with present perfect." },
]);

const PHYSICS_2017 = mk([
  { text: "SI unit of force is:", options: ["Newton", "Joule", "Watt", "Pascal"], answer: 0,
    explanation: "1 N = 1 kg·m/s²." },
  { text: "Acceleration due to gravity on Earth is approximately:", options: ["9.8 m/s²", "8.9 m/s²", "10.8 m/s²", "9.0 m/s²"], answer: 0,
    explanation: "Standard value near Earth's surface." },
  { text: "A car moves 100 m in 5 s. Its speed is:", options: ["20 m/s", "25 m/s", "10 m/s", "50 m/s"], answer: 0,
    explanation: "Speed = distance/time = 100/5." },
  { text: "The equation F = ma comes from:", options: ["Newton's 2nd law", "Newton's 1st law", "Newton's 3rd law", "Law of gravitation"], answer: 0,
    explanation: "Force equals mass times acceleration." },
  { text: "Kinetic energy of a 2 kg object moving at 3 m/s:", options: ["9 J", "6 J", "18 J", "3 J"], answer: 0,
    explanation: "KE = ½mv² = ½(2)(9) = 9 J." },
  { text: "The unit of electric current is:", options: ["Ampere", "Volt", "Ohm", "Coulomb"], answer: 0,
    explanation: "Ampere is the SI unit of current." },
  { text: "Ohm's law states V = ?", options: ["IR", "I/R", "R/I", "I + R"], answer: 0,
    explanation: "Voltage = current × resistance." },
  { text: "Which is a vector quantity?", options: ["Velocity", "Speed", "Mass", "Time"], answer: 0,
    explanation: "Vectors have magnitude and direction." },
  { text: "Frequency is measured in:", options: ["Hertz", "Second", "Meter", "Newton"], answer: 0,
    explanation: "1 Hz = 1 cycle per second." },
  { text: "Speed of light in vacuum is about:", options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "3 × 10⁵ m/s"], answer: 0,
    explanation: "c ≈ 299,792,458 m/s." },
  { text: "Momentum of a 5 kg body at 4 m/s:", options: ["20 kg·m/s", "9 kg·m/s", "1 kg·m/s", "40 kg·m/s"], answer: 0,
    explanation: "p = mv = 5 × 4 = 20." },
  { text: "The work done when 10 N moves an object 3 m in the force direction:", options: ["30 J", "13 J", "3 J", "10 J"], answer: 0,
    explanation: "W = F·d = 30 J." },
  { text: "Which type of lens forms only virtual images?", options: ["Concave", "Convex", "Plano-convex", "Bi-convex"], answer: 0,
    explanation: "Concave (diverging) lenses always form virtual images." },
  { text: "The device used to measure current is:", options: ["Ammeter", "Voltmeter", "Ohmmeter", "Galvanometer"], answer: 0,
    explanation: "Ammeter measures current in a circuit." },
  { text: "Sound cannot travel through:", options: ["Vacuum", "Air", "Water", "Solids"], answer: 0,
    explanation: "Sound requires a medium." },
  { text: "The SI unit of pressure is:", options: ["Pascal", "Newton", "Bar", "Joule"], answer: 0,
    explanation: "1 Pa = 1 N/m²." },
  { text: "In a series circuit, the current is:", options: ["Same everywhere", "Different in each resistor", "Zero", "Increasing"], answer: 0,
    explanation: "Series → current is constant." },
  { text: "Wavelength × frequency = ?", options: ["Speed", "Amplitude", "Period", "Phase"], answer: 0,
    explanation: "v = fλ." },
  { text: "The half-life of a radioactive substance is the time for its activity to:", options: ["Halve", "Double", "Vanish", "Stay constant"], answer: 0,
    explanation: "Half-life = time to reduce to half." },
  { text: "A force of 20 N acts on a mass of 4 kg. Acceleration = ?", options: ["5 m/s²", "80 m/s²", "16 m/s²", "24 m/s²"], answer: 0,
    explanation: "a = F/m = 20/4 = 5." },
]);

const CHEMISTRY_2017 = mk([
  { text: "Atomic number of oxygen:", options: ["8", "6", "16", "10"], answer: 0,
    explanation: "Oxygen has 8 protons." },
  { text: "Chemical symbol for gold:", options: ["Au", "Ag", "Gd", "Go"], answer: 0,
    explanation: "From Latin 'aurum'." },
  { text: "pH of pure water at 25°C:", options: ["7", "0", "14", "1"], answer: 0,
    explanation: "Neutral water has pH 7." },
  { text: "Which is a noble gas?", options: ["Neon", "Chlorine", "Sodium", "Iron"], answer: 0,
    explanation: "Neon is in Group 18." },
  { text: "Formula of water:", options: ["H₂O", "HO", "H₂O₂", "OH"], answer: 0,
    explanation: "Two hydrogens bonded to oxygen." },
  { text: "An acid turns blue litmus:", options: ["Red", "Blue", "Green", "Yellow"], answer: 0,
    explanation: "Acids turn blue litmus red." },
  { text: "Number of electrons in a neutral atom of carbon:", options: ["6", "12", "4", "8"], answer: 0,
    explanation: "Neutral atom → electrons = protons = 6." },
  { text: "Which bond involves sharing of electrons?", options: ["Covalent", "Ionic", "Metallic", "Hydrogen"], answer: 0,
    explanation: "Covalent bonds share electron pairs." },
  { text: "The main gas in Earth's atmosphere is:", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], answer: 0,
    explanation: "About 78% N₂." },
  { text: "Which subatomic particle has no charge?", options: ["Neutron", "Proton", "Electron", "Positron"], answer: 0,
    explanation: "Neutrons are electrically neutral." },
  { text: "Formula of sodium chloride:", options: ["NaCl", "Na₂Cl", "NaCl₂", "Na₂Cl₃"], answer: 0,
    explanation: "1:1 ratio of Na⁺ and Cl⁻." },
  { text: "Which is a strong acid?", options: ["HCl", "CH₃COOH", "H₂CO₃", "H₃PO₄"], answer: 0,
    explanation: "HCl fully ionises in water." },
  { text: "The mole is a unit for:", options: ["Amount of substance", "Mass", "Volume", "Concentration"], answer: 0,
    explanation: "1 mole = 6.022 × 10²³ particles." },
  { text: "Which state has definite shape and volume?", options: ["Solid", "Liquid", "Gas", "Plasma"], answer: 0,
    explanation: "Solids retain both shape and volume." },
  { text: "The process of solid → gas directly is:", options: ["Sublimation", "Evaporation", "Condensation", "Freezing"], answer: 0,
    explanation: "Sublimation skips the liquid phase." },
  { text: "Which element has the symbol 'K'?", options: ["Potassium", "Krypton", "Kryptonite", "Calcium"], answer: 0,
    explanation: "From Latin 'kalium'." },
  { text: "Oxidation is:", options: ["Loss of electrons", "Gain of electrons", "Gain of protons", "Loss of protons"], answer: 0,
    explanation: "OIL RIG: Oxidation Is Loss." },
  { text: "The most electronegative element is:", options: ["Fluorine", "Oxygen", "Chlorine", "Nitrogen"], answer: 0,
    explanation: "F has the highest electronegativity (~4.0)." },
  { text: "Which compound is an organic molecule?", options: ["CH₄", "NaCl", "H₂O", "CO₂"], answer: 0,
    explanation: "Methane is a hydrocarbon." },
  { text: "Avogadro's number is approximately:", options: ["6.022 × 10²³", "9.11 × 10⁻³¹", "3 × 10⁸", "1.6 × 10⁻¹⁹"], answer: 0,
    explanation: "Number of particles in one mole." },
]);

const BIOLOGY_2017 = mk([
  { text: "The basic unit of life is the:", options: ["Cell", "Tissue", "Organ", "Atom"], answer: 0,
    explanation: "All living things are made of cells." },
  { text: "The 'powerhouse' of the cell is:", options: ["Mitochondrion", "Nucleus", "Ribosome", "Golgi body"], answer: 0,
    explanation: "It produces ATP via cellular respiration." },
  { text: "DNA is found mainly in the:", options: ["Nucleus", "Cytoplasm", "Membrane", "Vacuole"], answer: 0,
    explanation: "Chromosomal DNA is in the nucleus." },
  { text: "Photosynthesis takes place in the:", options: ["Chloroplast", "Mitochondrion", "Nucleus", "Ribosome"], answer: 0,
    explanation: "Chlorophyll in chloroplasts captures light." },
  { text: "Blood is pumped by the:", options: ["Heart", "Liver", "Lungs", "Kidney"], answer: 0,
    explanation: "The heart is the circulatory pump." },
  { text: "Which is NOT a kingdom of living things?", options: ["Metallia", "Plantae", "Animalia", "Fungi"], answer: 0,
    explanation: "There is no kingdom named Metallia." },
  { text: "Human normal body temperature is about:", options: ["37°C", "40°C", "30°C", "45°C"], answer: 0,
    explanation: "Roughly 98.6°F = 37°C." },
  { text: "The male reproductive cell in flowering plants is found in:", options: ["Pollen", "Ovary", "Sepal", "Petal"], answer: 0,
    explanation: "Pollen carries male gametes." },
  { text: "Which blood cells fight infection?", options: ["White blood cells", "Red blood cells", "Platelets", "Plasma"], answer: 0,
    explanation: "Leukocytes are part of the immune response." },
  { text: "The exchange of gases in the lungs occurs in the:", options: ["Alveoli", "Bronchi", "Trachea", "Pharynx"], answer: 0,
    explanation: "Alveoli are the sites of gas exchange." },
  { text: "Mendel is known as the father of:", options: ["Genetics", "Evolution", "Ecology", "Anatomy"], answer: 0,
    explanation: "His pea plant experiments founded genetics." },
  { text: "An enzyme that breaks down starch is:", options: ["Amylase", "Lipase", "Protease", "Maltose"], answer: 0,
    explanation: "Amylase hydrolyses starch to sugars." },
  { text: "Green pigment in plants is:", options: ["Chlorophyll", "Xanthophyll", "Carotene", "Melanin"], answer: 0,
    explanation: "Chlorophyll absorbs light for photosynthesis." },
  { text: "Which vitamin is produced by skin in sunlight?", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin K"], answer: 0,
    explanation: "UV light triggers vitamin D synthesis." },
  { text: "Number of chromosomes in a normal human cell:", options: ["46", "23", "48", "44"], answer: 0,
    explanation: "23 pairs = 46 chromosomes." },
  { text: "The largest organ of the human body is the:", options: ["Skin", "Liver", "Heart", "Brain"], answer: 0,
    explanation: "Skin covers the whole body." },
  { text: "Cell division that produces gametes is:", options: ["Meiosis", "Mitosis", "Fission", "Budding"], answer: 0,
    explanation: "Meiosis halves chromosome number." },
  { text: "Which is a herbivore?", options: ["Cow", "Lion", "Eagle", "Shark"], answer: 0,
    explanation: "Herbivores feed on plants." },
  { text: "The functional unit of the kidney is the:", options: ["Nephron", "Neuron", "Alveolus", "Villus"], answer: 0,
    explanation: "Nephrons filter blood in the kidneys." },
  { text: "Which of the following is a virus disease?", options: ["Influenza", "Tuberculosis", "Cholera", "Malaria"], answer: 0,
    explanation: "Influenza is caused by influenza viruses." },
]);

const HISTORY_2017 = mk([
  { text: "The Battle of Adwa took place in:", options: ["1896", "1935", "1941", "1974"], answer: 0,
    explanation: "Ethiopian forces defeated Italy on 1 March 1896." },
  { text: "Emperor Menelik II is best known for:", options: ["Victory at Adwa", "Founding Axum", "Adopting Christianity", "Overthrowing the Derg"], answer: 0,
    explanation: "He led the Ethiopian army at Adwa." },
  { text: "Axum was a powerful kingdom located in:", options: ["Northern Ethiopia", "Southern Ethiopia", "Egypt", "Sudan"], answer: 0,
    explanation: "Axum flourished in what is today Tigray." },
  { text: "Ethiopia adopted Christianity in the:", options: ["4th century", "1st century", "10th century", "15th century"], answer: 0,
    explanation: "During the reign of King Ezana." },
  { text: "Emperor Haile Selassie was overthrown in:", options: ["1974", "1935", "1991", "1960"], answer: 0,
    explanation: "The 1974 Ethiopian revolution ended his rule." },
  { text: "The Derg was:", options: ["A military committee", "A royal family", "A religious order", "A political party"], answer: 0,
    explanation: "Provisional Military Administrative Council." },
  { text: "The Zagwe dynasty built the rock-hewn churches at:", options: ["Lalibela", "Gondar", "Axum", "Harar"], answer: 0,
    explanation: "King Lalibela commissioned them in the 12th–13th c." },
  { text: "Gondar became the capital of Ethiopia in the:", options: ["17th century", "13th century", "19th century", "20th century"], answer: 0,
    explanation: "Founded by Emperor Fasilides in 1636." },
  { text: "World War II ended in the year:", options: ["1945", "1939", "1918", "1950"], answer: 0,
    explanation: "The Axis powers surrendered in 1945." },
  { text: "The Cold War was between the USA and:", options: ["USSR", "China", "Germany", "Japan"], answer: 0,
    explanation: "Ideological rivalry after WWII." },
  { text: "The Organization of African Unity (OAU) was founded in:", options: ["1963", "1945", "1975", "1990"], answer: 0,
    explanation: "Founded in Addis Ababa on 25 May 1963." },
  { text: "The scramble for Africa peaked at the:", options: ["Berlin Conference (1884–85)", "Yalta Conference", "Congress of Vienna", "Versailles Treaty"], answer: 0,
    explanation: "European powers partitioned Africa there." },
  { text: "Italy invaded Ethiopia for a second time in:", options: ["1935", "1896", "1941", "1974"], answer: 0,
    explanation: "Mussolini launched the invasion in October 1935." },
  { text: "The current federal government of Ethiopia was established in:", options: ["1995", "1974", "1991", "2005"], answer: 0,
    explanation: "The FDRE constitution took effect in 1995." },
  { text: "Which empire is Ethiopia's Axum most closely linked to in trade?", options: ["Roman Empire", "Mongol Empire", "Ottoman Empire", "Aztec Empire"], answer: 0,
    explanation: "Axum traded via the Red Sea with Rome and beyond." },
  { text: "The French Revolution began in:", options: ["1789", "1776", "1848", "1815"], answer: 0,
    explanation: "Storming of the Bastille, 14 July 1789." },
  { text: "The Industrial Revolution began in:", options: ["Great Britain", "France", "Germany", "USA"], answer: 0,
    explanation: "It started in 18th-century Britain." },
  { text: "The United Nations was founded in:", options: ["1945", "1919", "1950", "1960"], answer: 0,
    explanation: "The UN Charter was signed in June 1945." },
  { text: "Emperor Tewodros II is remembered for:", options: ["Unifying Ethiopia in the 19th century", "Founding Axum", "Building Lalibela", "Adopting Christianity"], answer: 0,
    explanation: "He worked to reunify a fragmented Ethiopia." },
  { text: "The main cause of WWI was:", options: ["Assassination of Archduke Franz Ferdinand", "Great Depression", "Berlin Wall", "October Revolution"], answer: 0,
    explanation: "The 1914 assassination triggered the war." },
]);

const GEOGRAPHY_2017 = mk([
  { text: "The capital city of Ethiopia is:", options: ["Addis Ababa", "Dire Dawa", "Bahir Dar", "Mekelle"], answer: 0,
    explanation: "Addis Ababa is Ethiopia's political capital." },
  { text: "The longest river in Africa is the:", options: ["Nile", "Congo", "Niger", "Zambezi"], answer: 0,
    explanation: "The Nile is about 6,650 km long." },
  { text: "The Blue Nile originates from:", options: ["Lake Tana", "Lake Victoria", "Lake Turkana", "Lake Ziway"], answer: 0,
    explanation: "It flows out of Lake Tana in Ethiopia." },
  { text: "Ethiopia is located in:", options: ["East Africa", "West Africa", "North Africa", "Southern Africa"], answer: 0,
    explanation: "It is part of the Horn of Africa." },
  { text: "Which is the largest continent by area?", options: ["Asia", "Africa", "Europe", "North America"], answer: 0,
    explanation: "Asia covers about 44.5 million km²." },
  { text: "The Equator passes closest to which Ethiopian region?", options: ["Southern Ethiopia", "Northern Ethiopia", "Central Ethiopia", "Eastern Ethiopia"], answer: 0,
    explanation: "The southern border is nearest to 0°." },
  { text: "The highest mountain in Africa is:", options: ["Kilimanjaro", "Ras Dashen", "Kenya", "Meru"], answer: 0,
    explanation: "Mt. Kilimanjaro (5,895 m) is in Tanzania." },
  { text: "The Great Rift Valley runs through Ethiopia from:", options: ["North to South", "East to West", "West to East", "Nowhere"], answer: 0,
    explanation: "It runs roughly N–S across the country." },
  { text: "Which climate is typical of the Ethiopian highlands?", options: ["Temperate (Dega)", "Hot desert", "Tropical rainforest", "Polar"], answer: 0,
    explanation: "Highlands have cooler 'Dega' climate." },
  { text: "The main economic activity in Ethiopia is:", options: ["Agriculture", "Mining", "Manufacturing", "Tourism"], answer: 0,
    explanation: "Agriculture employs the majority." },
  { text: "Which lake is the largest in Ethiopia?", options: ["Lake Tana", "Lake Abaya", "Lake Ziway", "Lake Chamo"], answer: 0,
    explanation: "Lake Tana covers about 3,000 km²." },
  { text: "The Sahara Desert is located in:", options: ["North Africa", "South Africa", "East Africa", "West Africa"], answer: 0,
    explanation: "It stretches across northern Africa." },
  { text: "Latitude lines run:", options: ["East–West", "North–South", "Diagonally", "Vertically"], answer: 0,
    explanation: "Parallels of latitude are horizontal." },
  { text: "The Prime Meridian passes through:", options: ["Greenwich", "Paris", "New York", "Cairo"], answer: 0,
    explanation: "0° longitude runs through Greenwich, UK." },
  { text: "Which is a renewable resource?", options: ["Solar energy", "Coal", "Petroleum", "Natural gas"], answer: 0,
    explanation: "Sunlight is continually replenished." },
  { text: "Volcanoes are most common along:", options: ["Tectonic plate boundaries", "Ocean centres only", "Mountain summits only", "Equator"], answer: 0,
    explanation: "Plate boundaries host most volcanism." },
  { text: "The Suez Canal connects the Mediterranean Sea to:", options: ["Red Sea", "Arabian Sea", "Black Sea", "Persian Gulf"], answer: 0,
    explanation: "It shortens the Europe–Asia route." },
  { text: "A landlocked country has:", options: ["No coastline", "Long coastline", "Only rivers", "Only lakes"], answer: 0,
    explanation: "Landlocked = surrounded by land." },
  { text: "Ethiopia borders how many countries?", options: ["6", "5", "4", "7"], answer: 0,
    explanation: "Eritrea, Djibouti, Somalia, Kenya, South Sudan, Sudan." },
  { text: "Contour lines on a map join places of the same:", options: ["Altitude", "Temperature", "Population", "Rainfall"], answer: 0,
    explanation: "Contours show elevation." },
]);

const ECONOMICS_2017 = mk([
  { text: "Economics is best defined as the study of:", options: ["Scarcity and choice", "Only money", "Only banks", "Only trade"], answer: 0,
    explanation: "Economics studies allocation of scarce resources." },
  { text: "Opportunity cost is:", options: ["Value of the next-best alternative", "Money paid", "Free goods", "Total revenue"], answer: 0,
    explanation: "It's what you give up to get something." },
  { text: "In a market, price is set by the interaction of:", options: ["Demand and supply", "Government only", "Producers only", "Consumers only"], answer: 0,
    explanation: "Equilibrium price emerges from both sides." },
  { text: "If demand rises and supply is constant, price will:", options: ["Rise", "Fall", "Stay the same", "Disappear"], answer: 0,
    explanation: "Higher demand raises equilibrium price." },
  { text: "GDP stands for:", options: ["Gross Domestic Product", "Gross Direct Payment", "General Domestic Price", "Government Development Plan"], answer: 0,
    explanation: "Total value of goods and services produced within a country." },
  { text: "Inflation means a general rise in:", options: ["Prices", "Wages only", "Unemployment", "Interest only"], answer: 0,
    explanation: "It is a sustained rise in the price level." },
  { text: "A progressive tax is one that:", options: ["Rises with income", "Is the same for all", "Falls with income", "Applies only to companies"], answer: 0,
    explanation: "Higher earners pay a higher rate." },
  { text: "The central bank of Ethiopia is the:", options: ["National Bank of Ethiopia", "Commercial Bank of Ethiopia", "Awash Bank", "Dashen Bank"], answer: 0,
    explanation: "NBE is the monetary authority." },
  { text: "Which is a factor of production?", options: ["Labour", "Money", "Debt", "Price"], answer: 0,
    explanation: "Land, labour, capital, entrepreneurship." },
  { text: "A monopoly is a market with:", options: ["One seller", "Many sellers", "Two sellers", "Free entry"], answer: 0,
    explanation: "Monopoly = single seller with market power." },
  { text: "Micro-economics studies:", options: ["Individual markets", "The whole economy", "Global trade only", "Government policy only"], answer: 0,
    explanation: "It analyses firms and households." },
  { text: "A budget deficit means government spending is:", options: ["Greater than revenue", "Less than revenue", "Equal to revenue", "Zero"], answer: 0,
    explanation: "Spending > revenue → deficit." },
  { text: "Barter trade is:", options: ["Exchanging goods for goods", "Buying with cash", "Digital payment", "Selling on credit"], answer: 0,
    explanation: "Direct exchange without money." },
  { text: "The law of demand states:", options: ["Price ↑ → Quantity demanded ↓", "Price ↑ → Quantity demanded ↑", "No relationship", "Only supply matters"], answer: 0,
    explanation: "Inverse relationship, ceteris paribus." },
  { text: "Which is a stock (not a flow) variable?", options: ["Capital", "Income", "Savings per month", "Investment"], answer: 0,
    explanation: "Stock is measured at a point in time." },
  { text: "The main aim of a firm in a competitive market is to:", options: ["Maximise profit", "Minimise output", "Maximise costs", "Reduce prices to zero"], answer: 0,
    explanation: "Profit maximisation is the standard assumption." },
  { text: "Exports minus imports equals:", options: ["Net exports", "GDP", "Inflation", "Tax revenue"], answer: 0,
    explanation: "Net exports (NX) enter the trade balance." },
  { text: "The currency of Ethiopia is the:", options: ["Birr", "Shilling", "Dinar", "Franc"], answer: 0,
    explanation: "Ethiopian birr (ETB)." },
  { text: "Unemployment where workers move between jobs is called:", options: ["Frictional", "Structural", "Cyclical", "Seasonal"], answer: 0,
    explanation: "Short-term transitional unemployment." },
  { text: "A subsidy is a payment from:", options: ["Government to producers/consumers", "Consumers to firms", "Banks to government", "Foreign countries only"], answer: 0,
    explanation: "It lowers prices or boosts production." },
]);

const SAT_2017 = mk([
  { text: "If 3x + 5 = 20, then x = ?", options: ["5", "3", "8", "15"], answer: 0,
    explanation: "3x = 15 → x = 5." },
  { text: "Choose the word closest in meaning to 'meticulous':", options: ["Careful", "Careless", "Quick", "Loud"], answer: 0,
    explanation: "Meticulous = showing great attention to detail." },
  { text: "If y = 2x and x = 4, then y² = ?", options: ["64", "16", "8", "32"], answer: 0,
    explanation: "y = 8 → y² = 64." },
  { text: "Which is a synonym of 'ambiguous'?", options: ["Unclear", "Certain", "Bright", "Direct"], answer: 0,
    explanation: "Ambiguous = open to more than one interpretation." },
  { text: "The average of 4, 6, and 8 is:", options: ["6", "5", "7", "8"], answer: 0,
    explanation: "(4+6+8)/3 = 18/3 = 6." },
  { text: "Choose the correctly punctuated sentence:", options: ["It's raining outside.", "Its raining outside.", "Its' raining outside.", "It raining outside."], answer: 0,
    explanation: "It's = 'it is'." },
  { text: "If a triangle has angles 40° and 60°, the third angle is:", options: ["80°", "90°", "100°", "60°"], answer: 0,
    explanation: "180 − 40 − 60 = 80." },
  { text: "Antonym of 'obscure':", options: ["Clear", "Hidden", "Vague", "Dark"], answer: 0,
    explanation: "Obscure = unclear; opposite is clear." },
  { text: "A shirt costs $40 with a 25% discount. Sale price = ?", options: ["$30", "$25", "$35", "$32"], answer: 0,
    explanation: "40 − 25% × 40 = 40 − 10 = 30." },
  { text: "Which sentence uses parallel structure?", options: ["She likes running, swimming, and cycling.", "She likes to run, swimming and cycle.", "She like run, swim, and cycling.", "She likes run, swim, cycle."], answer: 0,
    explanation: "All three items are gerunds." },
  { text: "Solve: 2(x − 3) = 10", options: ["8", "5", "4", "7"], answer: 0,
    explanation: "x − 3 = 5 → x = 8." },
  { text: "Synonym of 'candid':", options: ["Honest", "Sneaky", "Silent", "Bright"], answer: 0,
    explanation: "Candid = truthful and straightforward." },
  { text: "In right triangle with legs 3 and 4, hypotenuse = ?", options: ["5", "6", "7", "√7"], answer: 0,
    explanation: "√(9 + 16) = 5." },
  { text: "Best word to fill: 'The evidence was ___ to convict him.'", options: ["sufficient", "sufficiency", "suffice", "suffered"], answer: 0,
    explanation: "An adjective is needed after 'was'." },
  { text: "If f(x) = x² − 4x + 3, then f(1) = ?", options: ["0", "1", "3", "−1"], answer: 0,
    explanation: "1 − 4 + 3 = 0." },
  { text: "Which is a run-on sentence?", options: ["I like tea I don't like coffee.", "I like tea, but I don't like coffee.", "I like tea. I don't like coffee.", "Although I like tea, I don't like coffee."], answer: 0,
    explanation: "Two independent clauses joined with no punctuation." },
  { text: "20% of 250 = ?", options: ["50", "25", "45", "60"], answer: 0,
    explanation: "0.20 × 250 = 50." },
  { text: "Antonym of 'benevolent':", options: ["Malevolent", "Kind", "Generous", "Cheerful"], answer: 0,
    explanation: "Malevolent = wishing evil on others." },
  { text: "If x² = 49, then x = ?", options: ["±7", "7 only", "−7 only", "49"], answer: 0,
    explanation: "Both 7 and −7 square to 49." },
  { text: "Choose the best transition: 'It rained heavily; ___, the match was cancelled.'", options: ["therefore", "however", "meanwhile", "although"], answer: 0,
    explanation: "'Therefore' expresses consequence." },
]);

// ─── Registry ────────────────────────────────────────────────────────────────

// Subject IDs come from EthioMatricApp:
// 1 Math, 2 English, 3 Physics, 4 Chemistry, 5 Biology,
// 6 History, 7 Geography, 8 Economics, 9 SAT
const PAPER_QUESTIONS: Record<number, Record<string, Question[]>> = {
  1: { "2017 E.C.": MATH_2017 },
  2: { "2017 E.C.": ENGLISH_2017 },
  3: { "2017 E.C.": PHYSICS_2017 },
  4: { "2017 E.C.": CHEMISTRY_2017 },
  5: { "2017 E.C.": BIOLOGY_2017 },
  6: { "2017 E.C.": HISTORY_2017 },
  7: { "2017 E.C.": GEOGRAPHY_2017 },
  8: { "2017 E.C.": ECONOMICS_2017 },
  9: { "2017 E.C.": SAT_2017 },
};

/**
 * Fetch the real questions for a given subject + year. Falls back to a
 * generated placeholder set when a paper hasn't been published yet.
 */
export function getPaperQuestions(
  subjectId: number,
  year: string,
  subjectName: string,
  fallbackCount = 20,
): Question[] {
  const real = PAPER_QUESTIONS[subjectId]?.[year];
  if (real && real.length > 0) return real;
  return Array.from({ length: fallbackCount }, (_, i) => ({
    id: i + 1,
    text: `[${subjectName} ${year}] Q${i + 1} — Paper not yet published. Sample placeholder question.`,
    options: [
      "Option A — Correct",
      "Option B",
      "Option C",
      "Option D",
    ],
    answer: 0,
    explanation: `This paper (${year}) has not been added yet. Option A is the placeholder correct answer.`,
  }));
}

export function hasRealPaper(subjectId: number, year: string): boolean {
  return !!PAPER_QUESTIONS[subjectId]?.[year];
}
